import { images } from "../constants";

export const restaurantData = [
  {
    id: 1,
    name: "Crispy Chicken Burgers",
    photo: images.crispy_chicken_burger,
    description: "Burgers with crispy chicken, cheese and lettuce",
    calories: 200,
    category: "AllCategories",
    price: 10,
  },
  {
    id: 2,
    name: "Crispy Chicken Burgers with Honey Mustard",
    photo: images.honey_mustard_chicken_burger,
    description: "Crispy Chicken Burgers with Honey Mustard Coleslaw",
    calories: 250,
    category: "Burgers",
    price: 15,
  },
  {
    id: 3,
    name: "Crispy Baked French Fries",
    photo: images.baked_fries,
    description: "Crispy Baked French Fries",
    calories: 194,
    category: "Burgers",
    price: 8,
  },

  {
    id: 4,
    name: "Hawaiian Pizza",
    photo: images.hawaiian_pizza,
    description: "Canadian bacon, homemade pizza crust, pizza sauce",
    calories: 250,
    category: "Pizza",
    price: 15,
  },
  {
    id: 5,
    name: "Tomato & Basil Pizza",
    photo: images.pizza,
    description: "Fresh tomatoes, aromatic basil pesto and melted bocconcini",
    calories: 250,
    category: "Pizza",
    price: 20,
  },
  {
    id: 6,
    name: "Tomato Pasta",
    photo: images.tomato_pasta,
    description: "Pasta with fresh tomatoes",
    calories: 100,
    category: "Pizza",
    price: 10,
  },
  {
    id: 7,
    name: "Mediterranean Chopped Salad ",
    photo: images.salad,
    description: "Finely chopped lettuce, tomatoes, cucumbers",
    calories: 100,
    category: "Pizza",
    price: 10,
  },

  {
    id: 8,
    name: "Chicago Style Hot Dog",
    photo: images.chicago_hot_dog,
    description: "Fresh tomatoes, all beef hot dogs",
    calories: 100,
    category: "HotDog",
    price: 20,
  },

  {
    id: 9,
    name: "Sushi sets",
    photo: images.sushi,
    description: "Fresh salmon, sushi rice, fresh juicy avocado",
    calories: 100,
    category: "Sushi",
    price: 50,
  },

  {
    id: 10,
    name: "Kolo Mee",
    photo: images.kolo_mee,
    description: "Noodles with char siu",
    calories: 200,
    category: "Noodles",
    price: 5,
  },
  {
    id: 11,
    name: "Sarawak Laksa",
    photo: images.sarawak_laksa,
    description: "Vermicelli noodles, cooked prawns",
    calories: 300,
    category: "Noodles",
    price: 8,
  },
  {
    id: 12,
    name: "Nasi Lemak",
    photo: images.nasi_lemak,
    description: "A traditional Malay rice dish",
    calories: 300,
    category: "Cuisine",
    price: 8,
  },
  {
    id: 13,
    name: "Nasi Briyani with Mutton",
    photo: images.nasi_briyani_mutton,
    description: "A traditional Indian rice dish with mutton",
    calories: 300,
    category: "Cuisine",
    price: 8,
  },

  {
    id: 14,
    name: "Teh C Peng",
    photo: images.teh_c_peng,
    description: "Three Layer Teh C Peng",
    calories: 100,
    category: "Desserts",
    price: 2,
  },
  {
    id: 15,
    name: "ABC Ice Kacang",
    photo: images.ice_kacang,
    description: "Shaved Ice with red beans",
    calories: 100,
    category: "Desserts",
    price: 3,
  },
  {
    id: 16,
    name: "Kek Lapis",
    photo: images.kek_lapis,
    description: "Layer cakes",
    calories: 300,
    category: "Desserts",
    price: 20,
  },
  {
    id: 17,
    name: "Kek Lapis",
    photo: images.kek_lapis,
    description: "Layer cakes",
    calories: 300,
    category: "Salads",
    price: 20,
  },
  {
    id: 18,
    name: "Kek Lapis",
    photo: images.kek_lapis,
    description: "Layer cakes",
    calories: 300,
    category: "Snacks",
    price: 20,
  },
  {
    id: 19,
    name: "Kek Lapis",
    photo: images.kek_lapis,
    description: "Layer cakes",
    calories: 300,
    category: "Drinks",
    price: 20,
  },
];
